services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tagging\Http\Api\Tag\:
        resource: '../../src/Http/Api/Tag/'

    App\Tagging\Http\Api\Tag\Responder\:
        resource: '../../src/Http/Api/Tag/Responder/'

    App\Tagging\Http\Api\Tag\Middleware\:
        resource: '../../src/Http/Api/Tag/Middleware/'
