services:
    PDO:
        class: PDO
        factory: ['App\Infrastructure\Persistence\Tag\PdoConnectionFactory', 'createFromEnvironment']

    App\Infrastructure\Persistence\Tag\PdoConnectionFactory: ~
