services:
    App\Infrastructure\ReadModel\Tag\TagReadModel:
        arguments:
            $pdo: '@PDO'

    App\Service\Core\Tag\TagReadModelInterface: '@App\Infrastructure\ReadModel\Tag\TagReadModel'
