services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tagging\Repository\Storage\:
        resource: '../../src/Repository/Storage/'

    App\Tagging\Reader\Model\:
        resource: '../../src/Reader/Model/'

    App\Tagging\Repository\Outbox\:
        resource: '../../src/Repository/Outbox/'

    App\Tagging\Factory\Config\:
        resource: '../../src/Factory/Config/'
