services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tagging\Cache\Security\:
        resource: '../../src/Cache/Security/'

    App\Tagging\Recorder\Metrics\:
        resource: '../../src/Recorder/Metrics/'

    App\Tagging\Reporter\Metrics\:
        resource: '../../src/Reporter/Metrics/'
