services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tagging\Service\Http\Tag\:
        resource: '../../src/Service/Http/Tag/'

    App\Tagging\Form\Type\:
        resource: '../../src/Form/Type/'
