imports:
  - { resource: '../services.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tagging\Repository\Storage\TagDoctrineRepository:
    public: true

  App\Tagging\Repository\TagReadModel:
    public: true

  App\Tagging\Service\Core\TagRepositoryInterface: '@App\Tagging\Repository\Storage\TagDoctrineRepository'
  App\Tagging\Service\Core\TagReadRepositoryInterface: '@App\Tagging\Repository\Storage\TagDoctrineRepository'
  App\Tagging\Service\Core\TagWriteRepositoryInterface: '@App\Tagging\Repository\Storage\TagDoctrineRepository'
  App\Tagging\Service\Core\TagPolicyRepositoryInterface: '@App\Tagging\Repository\Storage\TagDoctrineRepository'
  App\Tagging\Service\Core\TagCrudRepositoryInterface: '@App\Tagging\Repository\Storage\TagDoctrineRepository'
  App\Tagging\RepositoryInterface\TagReadModelInterface: '@App\Tagging\Repository\TagReadModel'
  App\Tagging\RepositoryInterface\TagTransactionRunnerInterface: '@App\Tagging\Repository\TagDoctrineTransactionRunner'
  App\Tagging\Service\Core\Webhook\TagWebhookRegistry:
    arguments:
      $path: '%kernel.project_dir%/report/webhook/registry.json'
  App\Tagging\Command\Console\:
    resource: '../../src/Command/Console/'
    autowire: true
    autoconfigure: true
